-- BluntChart — Supabase setup
--
-- REQUIRED: Run the migration once before checkout will work:
--   File: supabase/migrations/20250517000000_initial_schema.sql
--   Supabase Dashboard → SQL Editor → paste → Run
--
-- REQUIRED env vars (Vercel / .env.local):
--   NEXT_PUBLIC_SUPABASE_URL
--   NEXT_PUBLIC_SUPABASE_ANON_KEY
--   SUPABASE_SERVICE_ROLE_KEY  (server writes; do not expose to browser)
--
-- Verify after migration:
--   GET /api/health/db  →  { "ok": true }
--
-- Tables: users, payments, abandoned_checkouts, readings
