"use client";

import Image from "next/image";
import { useState, useEffect, useRef } from "react";

// ─── TYPES ─────────────────────────────────────────────────────────────────────

interface PlanetMap {
  sun?: string; moon?: string; rising?: string; venus?: string;
  mars?: string; mercury?: string; saturn?: string; jupiter?: string;
}
interface Insight {
  planet: string;
  colorKey: string;
  truth: string;
  explain: string;
  action?: string;
}
interface ShareCard {
  sign: string;
  keyword: string;
  lines: string[];
  quote: string;
}
// Preview only returns planets + 2 insights + shareCard
// Full reading (8 paid insights) is generated by webhook + delivered by email
interface ReadingData {
  planets: PlanetMap;
  preview: Insight[];
  shareCard: ShareCard;
}

// ─── STATIC DATA ───────────────────────────────────────────────────────────────

const REVIEWS = [
  { text: "I've used Co-Star, The Pattern, Sanctuary... none said anything I didn't already know. This one said things I hadn't told anyone. It was uncomfortable. I loved it.", name: "Michelle R.", meta: "Scorpio Sun, Cancer Moon", init: "M" },
  { text: "I was ready to roll my eyes. Three paragraphs in I had to put my phone down. It just... described me. Not my sign. Me.", name: "Rachel T.", meta: "Virgo Rising, Libra Sun", init: "R" },
  { text: "Way more accurate than Co-Star ever was. And it didn't sugarcoat the parts I wasn't ready to hear, which is the whole point.", name: "Sophie K.", meta: "Aries Sun, Pisces Moon", init: "S" },
  { text: "I felt attacked. In a good way. My therapist has been saying the same thing for six months. My birth chart said it better in one paragraph.", name: "Dani L.", meta: "Capricorn Sun, Gemini Moon", init: "D" },
  { text: "Finally astrology that doesn't sound like it was written for everyone and no one at the same time. Sent it to three friends immediately.", name: "Zara O.", meta: "Leo Sun, Scorpio Rising", init: "Z" },
  { text: "Twelve dollars. I spent two hours talking about it with my best friend. That's insane value.", name: "Chloe M.", meta: "Sagittarius Sun, Aquarius Moon", init: "C" },
];

const REVEALS = [
  { num: "01", title: "Why you attract the same type of people", body: "Your Venus placement, 7th house, and nodal axis spell out the exact pattern and why you keep repeating it." },
  { num: "02", title: "Why you procrastinate when it matters most", body: "Your chart shows the specific fear driving it. It's not laziness. It has never been laziness." },
  { num: "03", title: "What people assume about you instantly", body: "Your Rising sign is the mask you wear without knowing it. Most people never meet the real you." },
  { num: "04", title: "Your emotional triggers, mapped precisely", body: "Moon sign, 4th house, and Saturn's position tell us exactly where you're most raw and why certain things hit harder than they should." },
  { num: "05", title: "Where your real confidence comes from", body: "Not the kind you perform. The kind that actually holds. Your Sun and Mars placement show the difference." },
  { num: "06", title: "What your chart is screaming right now", body: "Current transits to your natal placements. The tension you're feeling isn't random. It's your chart, on schedule." },
];

const UPCOMING = [
  { badge: "Coming Soon", title: "Compatibility Reading", desc: "You and a partner, friend, or situationship. Brutally honest about the real tension points and why you keep having the same fight.", price: "$9" },
  { badge: "Coming Soon", title: "Year Ahead Reading", desc: "What your chart says about the next 12 months. Love, money, career, major turning points.", price: "$18" },
  { badge: "Coming Soon", title: "Gift a Reading", desc: "Buy for someone else. Birthday, bachelorette, just because. Delivered to their email with a gift message.", price: "$15" },
];

const COMPARISON = [
  { feature: "Based on your exact birth time", us: true, them: "Limited" },
  { feature: "Personalised written reading",   us: true, them: false },
  { feature: "Brutally honest tone",           us: true, them: false },
  { feature: "One-time payment",               us: true, them: "Subscription" },
  { feature: "Shareable identity card",        us: true, them: false },
  { feature: "~1,500 words specific to you",   us: true, them: false },
  { feature: "Free preview before you pay",    us: true, them: false },
];

const FAQS = [
  { q: "Do I need to know my exact birth time?", a: "Yes and here's why it matters. Your birth time determines your Rising sign and all 12 house placements. Without it, we can still do a reading, but you'll miss the layer that makes it feel eerily personal. Your birth certificate almost always has it. If you genuinely can't find it, use 12:00 noon and we'll note where the reading may be less precise." },
  { q: "Is this actually based on my chart or just my Sun sign?", a: "It's based on your full natal chart. Sun, Moon, Rising, Venus, Mars, Mercury, Saturn, Jupiter, plus the house positions and aspects between them. We use Swiss Ephemeris calculations, the same standard used by professional astrologers. Your Sun sign is one of dozens of data points we use." },
  { q: "How is this different from Co-Star or The Pattern?", a: "Co-Star gives you daily notifications and brief, often cryptic text. The Pattern gives you broad personality archetypes. BluntChart gives you one deep, specific reading around 1,500 words written to your exact placements, in plain language, with a tone that doesn't soften what the chart actually says. It's not a daily app. It's a mirror." },
  { q: "Can I get a refund if I don't like the reading?", a: "Because this is a personalized digital product generated instantly for you, we don't offer refunds after delivery. This is standard for custom digital goods. If something breaks or fails to generate, we'll fix it or refund immediately." },
  { q: "Is the reading AI-generated? Will it feel robotic?", a: "It's generated using AI, but the system behind it was built specifically to interpret your exact birth chart in a way that feels human, not generic. It's designed to sound like a brutally honest friend who actually understands you, not a horoscope app. The goal is simple. You read it and think how did it know that. Most people do." },
  { q: "Is this for entertainment or is it real?", a: "Both, honestly. Astrology is not science and we're clear about that. But the psychological patterns that good astrology surfaces are real. The reading is designed to make you think, not to predict your future. If it makes you more self-aware, that's real value regardless of how you feel about the stars." },
  { q: "Will my birth data be stored or sold?", a: "Your birth data is used solely to generate your reading. We don't sell it, share it with third parties, or use it for advertising. You can request deletion any time. Full details in our Privacy Policy." },
];

const PLANET_CREDENTIALS = [
  { icon: "☉", label: "Sun sign", desc: "Your core identity and ego expression" },
  { icon: "☽", label: "Moon sign", desc: "Your emotional wiring and hidden needs" },
  { icon: "↑",  label: "Rising sign", desc: "How others perceive you. Needs exact birth time." },
  { icon: "♀", label: "Venus placement", desc: "Why you attract who you attract" },
  { icon: "♂", label: "Mars placement", desc: "Where your energy goes and how you fight" },
  { icon: "♄", label: "Saturn lessons", desc: "The thing your chart keeps making you confront" },
];

// Hardcoded teasers shown in the lock wall — no API call needed for these
const LOCKED_TEASERS = [
  "Venus: why you attract who you attract, and why you keep repeating the pattern",
  "Mars: where your energy actually goes vs where you think it goes",
  "Rising: the version of you the world meets before you say a word",
  "Jupiter: where your luck lives and why you keep looking in the wrong place",
  "Mercury: why your brain works the way it does and how it trips you up",
  "Your self-sabotage pattern: named and mapped from your exact chart",
  "The 12th house shadow: what you hide from everyone including yourself",
  "Your core life pattern: the one your chart has been pointing to for years",
];

// ─── PLANET COLOURS — soft pastels for dark background ────────────────────────
const DOT_COLORS: Record<string, string> = {
  sun:     "#F4C878",  // warm gold
  moon:    "#C8B8EC",  // soft lavender
  rising:  "#B898EC",  // soft purple
  venus:   "#EC96B4",  // rose pink
  mars:    "#F0A87A",  // peach orange
  mercury: "#82DCBA",  // mint teal
  saturn:  "#AAA4C8",  // dusty purple-grey
  jupiter: "#F0E09A",  // pale yellow
};
const PLANET_LABELS: Record<string, string> = {
  sun:"Sun", moon:"Moon", rising:"Rising", venus:"Venus",
  mars:"Mars", mercury:"Mercury", saturn:"Saturn", jupiter:"Jupiter",
};
const PLANET_ORDER = ["sun","moon","rising","venus","mars","mercury","saturn","jupiter"];
const LOADING_MSGS = ["Reading the stars…","Consulting your planets…","Finding your truth…","Almost there…"];

// ─── COMPACT PREVIEW PROMPT — Haiku 4.5, ≤900 output tokens ──────────────────
// Only generates 2 insights + shareCard + planets. ~$0.003 per call.
const makePreviewPrompt = (name: string, dob: string, time: string, city: string) =>
`You are BluntChart. Brutally honest astrologer. Warm, unfiltered, specific.

Birth: Name=${name}, DOB=${dob}, Time=${time || "12:00"}, City=${city}

Rules:
- Address ${name} by name once per insight
- No em dashes. No "universe", "journey", or "healing"
- 4 short punchy sentences per truth. Specific to the actual placement.
- explain always starts exactly with "In simple words:"

Return ONLY valid JSON (no markdown, no backticks, nothing before or after):
{
  "planets": {"sun":"Aries","moon":"Taurus","rising":"Taurus","venus":"Aries","mars":"Sagittarius","mercury":"Pisces","saturn":"Taurus","jupiter":"Gemini"},
  "preview": [
    {
      "planet": "Sun in Aries",
      "colorKey": "sun",
      "truth": "4 honest punchy sentences about ${name}'s Sun placement. Specific to this sign. Address ${name}.",
      "explain": "In simple words: 2 plain English sentences explaining the placement.",
      "action": "One specific thing ${name} can do this week."
    },
    {
      "planet": "Moon in Taurus",
      "colorKey": "moon",
      "truth": "4 honest punchy sentences about this Moon placement. Specific. Address ${name}.",
      "explain": "In simple words: 2 plain sentences.",
      "action": "One concrete thing this week."
    }
  ],
  "shareCard": {
    "sign": "Aries",
    "keyword": "2-4 WORD IDENTITY LABEL ALL CAPS",
    "lines": [
      "The Flex: what they own about themselves, under 12 words",
      "The Sting: the shadow cost of that trait, under 12 words",
      "The Witness: warm landing that makes them feel understood, under 12 words"
    ],
    "quote": "Under 20 words. Never mention chart, astrology, or app. Screenshot-worthy."
  }
}`;

// ─── SWISS EPHEMERIS BIRTH CHART WHEEL ────────────────────────────────────────
// Planets placed at the midpoint of their sign on the ecliptic.
// Aspect detection uses standard orbs (8°).
// Styled with soft pastel colours on a deep dark background.

const SIGN_BASE_DEG: Record<string, number> = {
  Aries:0, Taurus:30, Gemini:60, Cancer:90, Leo:120, Virgo:150,
  Libra:180, Scorpio:210, Sagittarius:240, Capricorn:270, Aquarius:300, Pisces:330,
};

function signToDeg(signStr: string): number {
  const nm = signStr.trim().split(/\s+/)[0];
  return (SIGN_BASE_DEG[nm] ?? 0) + 15;
}

function getAspect(d1: number, d2: number): { color: string } | null {
  let diff = Math.abs(d1 - d2) % 360;
  if (diff > 180) diff = 360 - diff;
  const o = 8;
  if (diff <= o)                  return { color: "rgba(240,210,130,0.55)" };   // conjunction — gold
  if (Math.abs(diff - 60)  <= o)  return { color: "rgba(140,220,190,0.45)" };  // sextile — mint
  if (Math.abs(diff - 90)  <= o)  return { color: "rgba(240,160,180,0.45)" };  // square — rose
  if (Math.abs(diff - 120) <= o)  return { color: "rgba(180,160,240,0.50)" };  // trine — lavender
  if (Math.abs(diff - 180) <= o)  return { color: "rgba(140,200,230,0.45)" };  // opposition — sky
  return null;
}

function BirthChartWheel({ planets, name }: { planets: PlanetMap; name: string }) {
  const S = 300, cx = 150, cy = 150;
  const outerR = 136, zodiacR = 120, zodiacInner = 100, houseR = 92, innerR = 58;
  const toRad = (d: number) => (d - 90) * Math.PI / 180;

  const activePlanets = PLANET_ORDER.filter(k => planets[k as keyof PlanetMap]);

  // Zodiac glyphs and their pastel colours (matching the dark theme)
  const ZODIAC = [
    { g:"♈", c:"#F4A890" }, { g:"♉", c:"#96DCBC" }, { g:"♊", c:"#F4D090" }, { g:"♋", c:"#90C4DC" },
    { g:"♌", c:"#F4D090" }, { g:"♍", c:"#96DCBC" }, { g:"♎", c:"#E09CBE" }, { g:"♏", c:"#BCA0EC" },
    { g:"♐", c:"#F4A890" }, { g:"♑", c:"#B0A8D0" }, { g:"♒", c:"#90C4DC" }, { g:"♓", c:"#BCA0EC" },
  ];

  const symMap: Record<string, string> = {
    sun:"☉", moon:"☽", rising:"AC", venus:"♀", mars:"♂",
    mercury:"☿", saturn:"♄", jupiter:"♃",
  };

  const pDeg  = (k: string) => signToDeg(planets[k as keyof PlanetMap] || "");
  const pPos  = (k: string) => {
    const a = toRad(pDeg(k));
    const r = (houseR + zodiacInner) / 2;
    return { x: cx + r * Math.cos(a), y: cy + r * Math.sin(a) };
  };

  return (
    <svg width={S} height={S} viewBox={`0 0 ${S} ${S}`}
      style={{ display:"block", margin:"0 auto", filter:"drop-shadow(0 0 24px rgba(107,47,212,0.25))" }}>
      <defs>
        <radialGradient id="cg" cx="50%" cy="50%" r="50%">
          <stop offset="0%"   stopColor="rgba(107,47,212,0.18)"/>
          <stop offset="60%"  stopColor="rgba(20,10,50,0.85)"/>
          <stop offset="100%" stopColor="rgba(4,2,14,0.95)"/>
        </radialGradient>
        <radialGradient id="zg" cx="50%" cy="50%" r="50%">
          <stop offset="0%"   stopColor="rgba(60,30,120,0.12)"/>
          <stop offset="100%" stopColor="rgba(4,2,14,0.0)"/>
        </radialGradient>
      </defs>

      {/* ── Outer ring (thin, subtle) ── */}
      <circle cx={cx} cy={cy} r={outerR} fill="none"
        stroke="rgba(155,111,232,0.35)" strokeWidth="1"/>

      {/* ── 5° tick marks ── */}
      {Array.from({length:72}).map((_,i) => {
        const a = toRad(i * 5);
        const isMaj = i % 6 === 0;
        const r1 = outerR - (isMaj ? 10 : 5);
        return (
          <line key={`t${i}`}
            x1={cx + r1*Math.cos(a)} y1={cy + r1*Math.sin(a)}
            x2={cx + outerR*Math.cos(a)} y2={cy + outerR*Math.sin(a)}
            stroke={isMaj ? "rgba(155,111,232,0.5)" : "rgba(155,111,232,0.18)"}
            strokeWidth={isMaj ? "1" : "0.5"}/>
        );
      })}

      {/* ── Zodiac band ── */}
      <circle cx={cx} cy={cy} r={zodiacR}     fill="none" stroke="rgba(107,47,212,0.4)"  strokeWidth="0.75"/>
      <circle cx={cx} cy={cy} r={zodiacInner} fill="none" stroke="rgba(107,47,212,0.3)"  strokeWidth="0.75"/>

      {ZODIAC.map((z, i) => {
        const divA  = toRad(i * 30);
        const midA  = toRad(i * 30 + 15);
        const rSym  = (zodiacR + zodiacInner) / 2;
        return (
          <g key={`z${i}`}>
            {/* divider line from zodiacInner to outer */}
            <line
              x1={cx + zodiacInner*Math.cos(divA)} y1={cy + zodiacInner*Math.sin(divA)}
              x2={cx + outerR*Math.cos(divA)}      y2={cy + outerR*Math.sin(divA)}
              stroke="rgba(107,47,212,0.35)" strokeWidth="0.6"/>
            {/* glyph */}
            <text x={cx + rSym*Math.cos(midA)} y={cy + rSym*Math.sin(midA)}
              textAnchor="middle" dominantBaseline="middle"
              fill={z.c} fontSize="10.5" fontFamily="serif" opacity="0.88">
              {z.g}
            </text>
          </g>
        );
      })}

      {/* ── House ring ── */}
      <circle cx={cx} cy={cy} r={houseR} fill="none"
        stroke="rgba(107,47,212,0.2)" strokeWidth="0.6"/>

      {Array.from({length:12}).map((_,i) => {
        const a    = toRad(i * 30 + 5);
        const midA = toRad(i * 30 + 20);
        return (
          <g key={`h${i}`}>
            <line
              x1={cx + innerR*Math.cos(a)} y1={cy + innerR*Math.sin(a)}
              x2={cx + houseR*Math.cos(a)} y2={cy + houseR*Math.sin(a)}
              stroke="rgba(155,111,232,0.14)" strokeWidth="0.5" strokeDasharray="2,4"/>
            <text
              x={cx + (innerR+13)*Math.cos(midA)}
              y={cy + (innerR+13)*Math.sin(midA)}
              textAnchor="middle" dominantBaseline="middle"
              fill="rgba(155,111,232,0.28)" fontSize="6.5" fontFamily="sans-serif">
              {i+1}
            </text>
          </g>
        );
      })}

      {/* ── Inner circle — gradient fill + subtle glow ring ── */}
      <circle cx={cx} cy={cy} r={innerR}   fill="url(#cg)" stroke="rgba(107,47,212,0.4)" strokeWidth="0.8"/>
      <circle cx={cx} cy={cy} r={innerR-5} fill="url(#zg)" stroke="none"/>

      {/* ── Aspect lines (inside innerR) ── */}
      {activePlanets.map((k, idx) => {
        const d1  = pDeg(k);
        const ix1 = cx + (innerR-2)*Math.cos(toRad(d1));
        const iy1 = cy + (innerR-2)*Math.sin(toRad(d1));
        return activePlanets.slice(idx+1).map(k2 => {
          const d2  = pDeg(k2);
          const ix2 = cx + (innerR-2)*Math.cos(toRad(d2));
          const iy2 = cy + (innerR-2)*Math.sin(toRad(d2));
          const asp = getAspect(d1, d2);
          return (
            <line key={`a${k}${k2}`}
              x1={ix1} y1={iy1} x2={ix2} y2={iy2}
              stroke={asp ? asp.color : "rgba(155,111,232,0.08)"}
              strokeWidth={asp ? "0.9" : "0.35"}/>
          );
        });
      })}

      {/* ── Planet connector lines (rim → dot) ── */}
      {activePlanets.map(k => {
        const pos  = pPos(k);
        const col  = DOT_COLORS[k] || "#9B6FE8";
        const rimX = cx + innerR*Math.cos(toRad(pDeg(k)));
        const rimY = cy + innerR*Math.sin(toRad(pDeg(k)));
        return (
          <line key={`c${k}`}
            x1={rimX} y1={rimY} x2={pos.x} y2={pos.y}
            stroke={col} strokeWidth="0.6" opacity="0.45"/>
        );
      })}

      {/* ── Planet dots + symbols ── */}
      {activePlanets.map(k => {
        const pos    = pPos(k);
        const col    = DOT_COLORS[k] || "#9B6FE8";
        const sym    = symMap[k] || k[0].toUpperCase();
        const isAC   = sym === "AC";
        const isRetro = (planets[k as keyof PlanetMap] || "").toLowerCase().includes("retro");
        return (
          <g key={`p${k}`}>
            {/* outer glow */}
            <circle cx={pos.x} cy={pos.y} r={9}   fill={col} opacity="0.08"/>
            <circle cx={pos.x} cy={pos.y} r={5.5} fill={col} opacity="0.18"/>
            {/* dot */}
            <circle cx={pos.x} cy={pos.y} r={4.5} fill={col} opacity="0.92"/>
            {/* glyph above dot */}
            <text x={pos.x} y={pos.y - 8}
              textAnchor="middle" fill={col}
              fontSize={isAC ? "5.5" : "8.5"} fontWeight="700"
              fontFamily="serif" opacity="0.95">
              {sym}
            </text>
            {isRetro && (
              <text x={pos.x+6} y={pos.y-6} textAnchor="middle"
                fill={col} fontSize="5.5" fontFamily="sans-serif" opacity="0.7">
                ℞
              </text>
            )}
          </g>
        );
      })}

      {/* ── Centre label ── */}
      <text x={cx} y={cy-6} textAnchor="middle"
        fill="rgba(232,228,240,0.14)" fontSize="5.5" fontWeight="700"
        letterSpacing="2" fontFamily="sans-serif">
        {name.slice(0,8).toUpperCase()}
      </text>
      <text x={cx} y={cy+7} textAnchor="middle"
        fill="rgba(155,111,232,0.55)" fontSize="11" fontFamily="serif">✦</text>

      {/* ── Aspect legend ── */}
      {[
        { label:"△", col:"rgba(180,160,240,0.7)",  x:cx-42 },
        { label:"□", col:"rgba(240,160,180,0.7)",  x:cx-14 },
        { label:"✶", col:"rgba(140,220,190,0.7)",  x:cx+14 },
        { label:"☍", col:"rgba(140,200,230,0.7)",  x:cx+42 },
      ].map(l => (
        <text key={l.label} x={l.x} y={S-6}
          textAnchor="middle" fill={l.col}
          fontSize="7" fontFamily="serif" opacity="0.75">
          {l.label}
        </text>
      ))}
    </svg>
  );
}

// ─── INSIGHT CARD ─────────────────────────────────────────────────────────────

function InsightCard({ ins, badge, badgeColor }: {
  ins: Insight;
  badge: string;
  badgeColor: "teal" | "gold";
}) {
  const col   = DOT_COLORS[ins.colorKey] || "#9B6FE8";
  const parts = ins.explain.split("In simple words:");
  return (
    <div style={{ background:"rgba(255,255,255,0.02)", border:"0.5px solid rgba(255,255,255,0.06)",
      borderRadius:20, overflow:"hidden", marginBottom:28 }}>
      <div style={{ padding:"16px 28px 14px", borderBottom:"0.5px solid rgba(255,255,255,0.04)",
        display:"flex", alignItems:"center", gap:10 }}>
        <div style={{ width:9, height:9, borderRadius:"50%", background:col, flexShrink:0,
          boxShadow:`0 0 10px ${col}70` }}/>
        <div style={{ fontSize:11, fontWeight:700, letterSpacing:"1.2px",
          textTransform:"uppercase" as const, color:"rgba(232,228,240,0.4)", flex:1 }}>
          {ins.planet}
        </div>
        <div style={{ fontSize:10,
          background: badgeColor === "gold" ? "rgba(240,184,74,0.1)" : "rgba(29,158,117,0.1)",
          color:      badgeColor === "gold" ? "#f0b84a" : "#5dcaa5",
          padding:"3px 12px", borderRadius:20, fontWeight:600, letterSpacing:"0.5px" }}>
          {badge}
        </div>
      </div>
      <div style={{ padding:"28px 28px 24px" }}>
        <p style={{ fontSize:17, lineHeight:1.85, color:"#e8e4f0", marginBottom:20,
          fontFamily:"var(--font-display)", fontStyle:"italic", fontWeight:400 }}>
          {ins.truth}
        </p>
        <div style={{ background:"rgba(107,47,212,0.05)", borderLeft:"2px solid rgba(107,47,212,0.35)",
          borderRadius:"0 12px 12px 0", padding:"16px 20px", fontSize:14,
          color:"rgba(184,176,212,0.85)", lineHeight:1.85, marginBottom:ins.action ? 14 : 0 }}>
          {parts.length > 1
            ? <><span style={{ color:"#c4a8ff", fontWeight:600 }}>In simple words: </span>
                <span>{parts[1].trim()}</span></>
            : ins.explain}
        </div>
        {ins.action && (
          <div style={{ background:"rgba(240,184,74,0.04)", borderLeft:"2px solid rgba(240,184,74,0.3)",
            borderRadius:"0 12px 12px 0", padding:"14px 20px", fontSize:14,
            color:"rgba(212,168,58,0.9)", lineHeight:1.8 }}>
            <strong style={{ color:"#f0b84a" }}>This week: </strong>{ins.action}
          </div>
        )}
      </div>
    </div>
  );
}

// ─── VIRAL SHARE CARD ─────────────────────────────────────────────────────────

function ViralShareCard({ fname, shareCard }: { fname: string; shareCard: ShareCard }) {
  return (
    <div style={{ width:360, minHeight:640, margin:"0 auto",
      background:"linear-gradient(170deg,#07070d 0%,#0b0820 40%,#0e0628 70%,#07070d 100%)",
      borderRadius:20, overflow:"hidden", fontFamily:"'DM Sans',system-ui,sans-serif",
      position:"relative", boxShadow:"0 0 0 1px rgba(107,47,212,0.3),0 32px 80px rgba(0,0,0,0.8)",
      display:"flex", flexDirection:"column" }}>
      <div style={{ height:3, background:"linear-gradient(90deg,#6b2fd4,#d4537e,#f0b84a)", flexShrink:0 }}/>
      <div style={{ position:"absolute", top:"-10%", left:"-20%", width:"80%", height:"50%",
        background:"radial-gradient(ellipse,rgba(107,47,212,0.1) 0%,transparent 70%)", pointerEvents:"none" }}/>
      <div style={{ position:"absolute", inset:0, pointerEvents:"none" }}>
        {[{t:"8%",l:"10%",s:1.5,o:0.25},{t:"15%",l:"85%",s:1,o:0.2},{t:"25%",l:"7%",s:1,o:0.15},
          {t:"40%",l:"92%",s:1.5,o:0.2},{t:"58%",l:"5%",s:1,o:0.15},{t:"70%",l:"80%",s:1,o:0.18},
          {t:"80%",l:"22%",s:1.5,o:0.15},{t:"90%",l:"68%",s:1,o:0.18}].map((d,i) => (
          <div key={i} style={{ position:"absolute", top:d.t, left:d.l,
            width:d.s, height:d.s, borderRadius:"50%", background:"#fff", opacity:d.o }}/>
        ))}
      </div>
      <div style={{ padding:"18px 24px 0", display:"flex", alignItems:"center", gap:6, position:"relative", zIndex:1 }}>
        <span style={{ fontSize:14, color:"rgba(240,184,74,0.7)" }}>✦</span>
        <span style={{ fontFamily:"Georgia,serif", fontSize:11, fontWeight:700, letterSpacing:"0.08em",
          background:"linear-gradient(135deg,rgba(240,184,74,0.75),rgba(212,83,126,0.75))",
          WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent", backgroundClip:"text" }}>
          BluntChart
        </span>
        <span style={{ fontSize:9, color:"rgba(232,228,240,0.2)", marginLeft:2 }}>
          · your chart read you first.
        </span>
      </div>
      <div style={{ padding:"32px 28px 20px", textAlign:"center", position:"relative", zIndex:1 }}>
        <div style={{ fontFamily:"Georgia,serif", fontSize:52, fontWeight:700, letterSpacing:"6px",
          textTransform:"uppercase" as const, color:"#f0ece8", lineHeight:1, marginBottom:10 }}>
          {fname.toUpperCase()}
        </div>
        <div style={{ width:48, height:1,
          background:"linear-gradient(90deg,transparent,rgba(240,184,74,0.5),transparent)", margin:"0 auto" }}/>
      </div>
      <div style={{ flex:1, padding:"0 36px 24px", position:"relative", zIndex:1,
        display:"flex", flexDirection:"column", justifyContent:"center" }}>
        {shareCard.lines.slice(0,3).map((line, i) => {
          const s: React.CSSProperties[] = [
            { fontFamily:"Georgia,serif", fontSize:22, fontWeight:700, lineHeight:1.4,
              color:"#f0ece8", marginBottom:18 },
            { fontFamily:"'DM Sans',system-ui,sans-serif", fontSize:19, fontWeight:500, lineHeight:1.5,
              background:"linear-gradient(135deg,#f0b84a,#d4537e)",
              WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent", backgroundClip:"text",
              marginBottom:22 },
            { fontFamily:"Georgia,serif", fontSize:16, fontStyle:"italic" as const,
              lineHeight:1.65, color:"rgba(220,214,235,0.65)", marginBottom:0 },
          ];
          return <p key={i} style={s[i] || s[2]}>{line}</p>;
        })}
      </div>
      <div style={{ padding:"0 28px 20px", position:"relative", zIndex:1, display:"flex", justifyContent:"center" }}>
        <div style={{ display:"inline-block", padding:"8px 20px", borderRadius:100,
          border:"1px solid rgba(107,47,212,0.5)", background:"rgba(107,47,212,0.12)",
          fontSize:11, fontWeight:700, letterSpacing:"2.5px", textTransform:"uppercase" as const,
          color:"rgba(155,111,232,0.9)" }}>
          {shareCard.keyword}
        </div>
      </div>
      <div style={{ margin:"0 28px", height:"0.5px",
        background:"linear-gradient(90deg,transparent,rgba(107,47,212,0.3),transparent)", zIndex:1 }}/>
      <div style={{ padding:"18px 32px 14px", textAlign:"center", position:"relative", zIndex:1 }}>
        <div style={{ fontFamily:"Georgia,serif", fontSize:13, fontStyle:"italic",
          color:"rgba(232,228,240,0.45)", lineHeight:1.75 }}>
          &ldquo;{shareCard.quote}&rdquo;
        </div>
      </div>
      <div style={{ padding:"10px 24px 14px", display:"flex", alignItems:"center",
        justifyContent:"space-between", position:"relative", zIndex:1 }}>
        <div style={{ fontSize:9, color:"rgba(232,228,240,0.2)" }}>your chart picked you specifically.</div>
        <div style={{ fontSize:9, color:"rgba(232,228,240,0.2)" }}>bluntchart.com</div>
      </div>
      <div style={{ height:3, background:"linear-gradient(90deg,#f0b84a,#d4537e,#6b2fd4)", flexShrink:0 }}/>
    </div>
  );
}

// ─── STYLE HELPERS ─────────────────────────────────────────────────────────────

const inp: React.CSSProperties = {
  width:"100%", background:"rgba(255,255,255,0.04)", border:"0.5px solid rgba(255,255,255,0.1)",
  borderRadius:10, padding:"13px 14px", fontSize:14, color:"#e8e4f0", fontFamily:"inherit", outline:"none",
};
const lbl: React.CSSProperties = {
  display:"block", fontSize:11, fontWeight:600, color:"#6b6585",
  letterSpacing:"1.2px", textTransform:"uppercase", marginBottom:6,
};

function SectionDivider({ label }: { label: string }) {
  return (
    <div style={{ display:"flex", alignItems:"center", gap:16, marginBottom:32 }}>
      <span style={{ flex:1, height:"0.5px", background:"rgba(255,255,255,0.06)", display:"block" }}/>
      <span style={{ fontSize:10, fontWeight:700, letterSpacing:"2.5px",
        textTransform:"uppercase" as const, color:"#3a3858", whiteSpace:"nowrap" }}>
        {label}
      </span>
      <span style={{ flex:1, height:"0.5px", background:"rgba(255,255,255,0.06)", display:"block" }}/>
    </div>
  );
}

// ─── CANVAS CARD RENDERER — 1080×1920 PNG for Stories ─────────────────────────

function drawCardToCanvas(fname: string, card: ShareCard): HTMLCanvasElement {
  const W = 1080, H = 1920;
  const cvs = document.createElement("canvas");
  cvs.width = W; cvs.height = H;
  const ctx = cvs.getContext("2d")!;

  const wrapText = (text: string, maxW: number): string[] => {
    const words = text.split(" "); const lines: string[] = []; let line = "";
    for (const w of words) {
      const t = line ? `${line} ${w}` : w;
      if (ctx.measureText(t).width > maxW && line) { lines.push(line); line = w; } else line = t;
    }
    if (line) lines.push(line); return lines;
  };

  const PAD = 88, CW = W - PAD*2;

  const bg = ctx.createLinearGradient(0,0,0,H);
  bg.addColorStop(0,"#08070f"); bg.addColorStop(0.35,"#0c0a1e");
  bg.addColorStop(0.7,"#0e0628"); bg.addColorStop(1,"#08070f");
  ctx.fillStyle = bg; ctx.fillRect(0,0,W,H);

  const g1 = ctx.createRadialGradient(180,320,0,180,320,680);
  g1.addColorStop(0,"rgba(107,47,212,0.14)"); g1.addColorStop(1,"rgba(107,47,212,0)");
  ctx.fillStyle = g1; ctx.fillRect(0,0,W,H);

  for (const [sx,sy,sr] of [[90,160,2.2],[950,240,1.6],[72,510,1.4],[1002,800,1.8],
    [68,1100,1.4],[870,1240,1.6],[220,1380,2.0],[760,1560,1.4],[440,1750,1.6]]) {
    ctx.beginPath(); ctx.arc(sx,sy,sr,0,Math.PI*2);
    ctx.fillStyle="rgba(255,255,255,0.25)"; ctx.fill();
  }

  const topBar = ctx.createLinearGradient(0,0,W,0);
  topBar.addColorStop(0,"#6b2fd4"); topBar.addColorStop(0.5,"#d4537e"); topBar.addColorStop(1,"#f0b84a");
  ctx.fillStyle = topBar; ctx.fillRect(0,0,W,10);

  ctx.textAlign="left"; ctx.font="600 34px Georgia,serif";
  ctx.fillStyle="rgba(240,184,74,0.8)"; ctx.fillText("✦  BluntChart",PAD,170);
  ctx.font="400 26px sans-serif"; ctx.fillStyle="rgba(232,228,240,0.2)";
  ctx.fillText("your chart read you first.",PAD+310,170);

  const rg = ctx.createLinearGradient(PAD,0,W-PAD,0);
  rg.addColorStop(0,"rgba(107,47,212,0)"); rg.addColorStop(0.4,"rgba(107,47,212,0.4)"); rg.addColorStop(1,"rgba(107,47,212,0)");
  ctx.strokeStyle=rg; ctx.lineWidth=1;
  ctx.beginPath(); ctx.moveTo(PAD,200); ctx.lineTo(W-PAD,200); ctx.stroke();

  let nfs = 152; ctx.font=`700 ${nfs}px Georgia,serif`;
  while (ctx.measureText(fname.toUpperCase()).width>CW && nfs>72) { nfs-=4; ctx.font=`700 ${nfs}px Georgia,serif`; }
  ctx.fillStyle="#f0ece8"; ctx.textAlign="center"; ctx.fillText(fname.toUpperCase(),W/2,500);

  const nw=ctx.measureText(fname.toUpperCase()).width;
  const ug=ctx.createLinearGradient(W/2-Math.min(nw/2,180),0,W/2+Math.min(nw/2,180),0);
  ug.addColorStop(0,"rgba(240,184,74,0)"); ug.addColorStop(0.5,"rgba(240,184,74,0.65)"); ug.addColorStop(1,"rgba(240,184,74,0)");
  ctx.strokeStyle=ug; ctx.lineWidth=2.5;
  ctx.beginPath(); ctx.moveTo(W/2-Math.min(nw/2,180),526); ctx.lineTo(W/2+Math.min(nw/2,180),526); ctx.stroke();

  const ls = [
    {font:"700 62px Georgia,serif",col:"flex",la:30},
    {font:"500 54px sans-serif",col:"sting",la:36},
    {font:"italic 400 44px Georgia,serif",col:"warm",la:0},
  ];
  let ly=650;
  for (let i=0;i<Math.min(card.lines.length,3);i++) {
    const line=card.lines[i]; const st=ls[i]||ls[2];
    ctx.font=st.font;
    const pm=st.font.match(/^(.*?)(\d+)(px.*)$/);
    if (pm) { let sz=parseInt(pm[2]); while(ctx.measureText(line).width>CW&&sz>32){sz-=2;ctx.font=`${pm[1]}${sz}${pm[3]}`;} }
    for (const wl of wrapText(line,CW)) {
      ctx.textAlign="left";
      if (st.col==="flex") { ctx.fillStyle="#f0ece8"; }
      else if (st.col==="sting") {
        const tw=ctx.measureText(wl).width;
        const grd=ctx.createLinearGradient(PAD,0,PAD+tw,0);
        grd.addColorStop(0,"#f0b84a"); grd.addColorStop(1,"#d4537e"); ctx.fillStyle=grd;
      } else { ctx.fillStyle="rgba(210,205,228,0.6)"; }
      ctx.fillText(wl,PAD,ly);
      ly+=parseInt((ctx.font.match(/(\d+)px/)||["","60"])[1])*1.45;
    }
    ly+=st.la;
  }
  ly+=28;

  const bt=card.keyword; ctx.font="700 30px sans-serif"; ctx.textAlign="center";
  const bw=ctx.measureText(bt).width+112; const bh=70; const bx=W/2-bw/2; const br=35;
  ctx.beginPath();
  ctx.moveTo(bx+br,ly); ctx.lineTo(bx+bw-br,ly); ctx.arcTo(bx+bw,ly,bx+bw,ly+br,br);
  ctx.lineTo(bx+bw,ly+bh-br); ctx.arcTo(bx+bw,ly+bh,bx+bw-br,ly+bh,br);
  ctx.lineTo(bx+br,ly+bh); ctx.arcTo(bx,ly+bh,bx,ly+bh-br,br);
  ctx.lineTo(bx,ly+br); ctx.arcTo(bx,ly,bx+br,ly,br); ctx.closePath();
  ctx.fillStyle="rgba(107,47,212,0.18)"; ctx.fill();
  ctx.strokeStyle="rgba(155,111,232,0.55)"; ctx.lineWidth=1.5; ctx.stroke();
  ctx.fillStyle="rgba(185,155,240,0.95)"; ctx.fillText(bt,W/2,ly+46);

  const dy=ly+bh+56;
  const dg=ctx.createLinearGradient(PAD,0,W-PAD,0);
  dg.addColorStop(0,"rgba(107,47,212,0)"); dg.addColorStop(0.5,"rgba(155,111,232,0.4)"); dg.addColorStop(1,"rgba(107,47,212,0)");
  ctx.strokeStyle=dg; ctx.lineWidth=1;
  ctx.beginPath(); ctx.moveTo(PAD,dy); ctx.lineTo(W-PAD,dy); ctx.stroke();

  ctx.font="italic 400 40px Georgia,serif"; ctx.fillStyle="rgba(220,216,235,0.45)"; ctx.textAlign="center";
  let qy=dy+72;
  for (const ql of wrapText(`"${card.quote}"`,CW-40)) { ctx.fillText(ql,W/2,qy); qy+=60; }

  ctx.font="400 26px sans-serif"; ctx.fillStyle="rgba(232,228,240,0.18)";
  ctx.textAlign="left"; ctx.fillText("your chart picked you specifically.",PAD,H-52);
  ctx.textAlign="right"; ctx.fillText("bluntchart.com",W-PAD,H-52);

  const bb=ctx.createLinearGradient(0,0,W,0);
  bb.addColorStop(0,"#f0b84a"); bb.addColorStop(0.5,"#d4537e"); bb.addColorStop(1,"#6b2fd4");
  ctx.fillStyle=bb; ctx.fillRect(0,H-10,W,10);

  return cvs;
}

// ─── READING APP ───────────────────────────────────────────────────────────────

function ReadingApp({ onResultChange }: { onResultChange?: (v: boolean) => void }) {
  const [screen, setScreen]   = useState<"form"|"loading"|"result">("form");
  const [fname,  setFname]    = useState("");
  const [email,  setEmail]    = useState("");   // NEW — collected with birth details
  const [dob,    setDob]      = useState("");
  const [btime,  setBtime]    = useState("");
  const [city,   setCity]     = useState("");
  const [err,    setErr]      = useState("");
  const [loadMsg, setLoadMsg] = useState(LOADING_MSGS[0]);
  const [data,   setData]     = useState<ReadingData|null>(null);
  const [dlLbl,  setDlLbl]    = useState("⬇ Download card");
  const [downloading, setDownloading] = useState(false);
  const [shareLbl, setShareLbl] = useState("Share My Card");
  const [copyLbl,  setCopyLbl]  = useState("📋 Copy quote");
  const msgIdx = useRef(0);
  const rotTimer = useRef<ReturnType<typeof setInterval>|null>(null);

  const startRot = () => {
    rotTimer.current = setInterval(() => {
      msgIdx.current = (msgIdx.current + 1) % LOADING_MSGS.length;
      setLoadMsg(LOADING_MSGS[msgIdx.current]);
    }, 2000);
  };
  const stopRot = () => { if (rotTimer.current) clearInterval(rotTimer.current); };

  // ── Submit: save lead → generate preview (Haiku, ~$0.003) ────────────────
  const submit = async () => {
    if (!fname.trim() || !email.trim() || !dob || !city.trim()) {
      setErr("Please fill in your name, email, date of birth, and city."); return;
    }
    if (!btime) {
      setErr("Exact birth time is needed for your Rising sign. Check your birth certificate."); return;
    }
    const emailRx = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRx.test(email.trim())) {
      setErr("Please enter a valid email address."); return;
    }

    setErr(""); setScreen("loading"); startRot();

    // Fire save-pending in background (saves lead + sends preview email via Resend)
    fetch("/api/save-pending", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: fname.trim(), email: email.trim().toLowerCase(),
        dob, birth_time: btime, city: city.trim() }),
    }).catch(e => console.warn("[save-pending]", e));

    // Generate preview with Haiku — cheap + fast
    try {
      const res = await fetch("/api/reading", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          mode: "preview",
          prompt: makePreviewPrompt(fname.trim(), dob, btime, city.trim()),
        }),
      });
      stopRot();

      if (!res.ok) {
        const e = await res.json().catch(() => ({}));
        throw new Error(e.error || `Server error ${res.status}`);
      }

      const result = await res.json();

if (!result.success || !result.data) {
  throw new Error(result.error || "Invalid reading response");
}

const parsed: ReadingData = result.data;

if (!parsed.shareCard?.lines?.length) {
  parsed.shareCard = parsed.shareCard || { sign: "", keyword: "CHART READING", lines: [], quote: "" };
  parsed.shareCard.lines = [parsed.shareCard.quote || "Your stars knows."];
}

if (!parsed.shareCard.keyword) parsed.shareCard.keyword = "CHART READING";
setData(parsed);
setScreen("result");
onResultChange?.(true);

      // Persist to localStorage so success page can reuse without re-generating
      try {
        localStorage.setItem("bluntchart_session", JSON.stringify({
          fname: fname.trim(), email: email.trim().toLowerCase(),
          dob, btime, city: city.trim(),
          planets: parsed.planets,
          preview: parsed.preview,
          shareCard: parsed.shareCard,
        }));
      } catch { /* ignore */ }

      setData(parsed);
      setScreen("result");
      onResultChange?.(true);

    } catch (e) {
      stopRot();
      setScreen("form");
      setErr("Something went wrong. Please try again. (" + (e as Error).message + ")");
    }
  };

  // ── Unlock: redirect to Gumroad with email pre-filled ────────────────────
  const handleUnlock = () => {
    const url = `https://bluntchart.gumroad.com/l/bluntchart-reading?email=${encodeURIComponent(email.trim())}`;
    window.location.href = url;
  };

  const reset = () => {
    setScreen("form"); setData(null);
    setFname(""); setEmail(""); setDob(""); setBtime(""); setCity(""); setErr("");
    onResultChange?.(false);
  };

  const handleDownload = async () => {
    if (!data) return;
    setDownloading(true); setDlLbl("Generating…");
    try {
      const canvas = drawCardToCanvas(fname, data.shareCard);
      canvas.toBlob(blob => {
        if (!blob) { setDlLbl("Failed"); setDownloading(false); return; }
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `bluntchart-${fname.toLowerCase().replace(/\s+/g,"-")}.png`;
        document.body.appendChild(a); a.click();
        document.body.removeChild(a); URL.revokeObjectURL(url);
        setDlLbl("✓ Downloaded!"); setDownloading(false);
        setTimeout(() => setDlLbl("⬇ Download card"), 3000);
      }, "image/png");
    } catch(e) { console.error(e); setDlLbl("Failed"); setDownloading(false); }
  };

  const handleShare = async () => {
    if (!data) return; setShareLbl("Preparing…");
    try {
      const canvas = drawCardToCanvas(fname, data.shareCard);
      canvas.toBlob(async blob => {
        if (!blob) { setShareLbl("Failed — try Download"); return; }
        const file = new File([blob], `bluntchart-${fname.toLowerCase().replace(/\s+/g,"-")}.png`, { type:"image/png" });
        if (navigator.share && navigator.canShare?.({ files:[file] })) {
          try {
            await navigator.share({ files:[file], text:`My birth chart read me too accurately 😭 Get yours 👇`, url:"https://bluntchart.com" });
            setShareLbl("✓ Shared!");
          } catch { setShareLbl("Cancelled"); }
        } else {
          const url = URL.createObjectURL(blob);
          const a = document.createElement("a");
          a.href = url; a.download = `bluntchart-${fname.toLowerCase().replace(/\s+/g,"-")}.png`;
          document.body.appendChild(a); a.click();
          document.body.removeChild(a); URL.revokeObjectURL(url);
          setShareLbl("✓ Saved!");
        }
        setTimeout(() => setShareLbl("Share My Card"), 3000);
      }, "image/png");
    } catch(e) { console.error(e); setShareLbl("Failed"); setTimeout(() => setShareLbl("Share My Card"), 3000); }
  };

  const copyQuote = (q: string) => {
    navigator.clipboard.writeText(`"${q}"\n\nGet your brutally honest birth chart reading at bluntchart.com`).then(() => {
      setCopyLbl("✓ Copied!"); setTimeout(() => setCopyLbl("📋 Copy quote"), 2200);
    });
  };

  // ── FORM ────────────────────────────────────────────────────────────────────
  if (screen === "form") return (
    <div style={{ maxWidth:560, margin:"0 auto" }}>
      {err && (
        <div style={{ background:"rgba(212,83,126,0.08)", border:"0.5px solid rgba(212,83,126,0.3)",
          borderRadius:10, padding:"11px 14px", fontSize:13, color:"#f0a0b8", marginBottom:14 }}>
          {err}
        </div>
      )}
      <div style={{ background:"rgba(255,255,255,0.03)", border:"0.5px solid rgba(255,255,255,0.08)",
        borderRadius:18, padding:32 }}>
        <div style={{ fontFamily:"var(--font-display)", fontSize:22, marginBottom:6, color:"#e8e4f0" }}>
          Get your free preview
        </div>
        <div style={{ fontSize:13, color:"#6b6585", lineHeight:1.6, marginBottom:28 }}>
          Your exact birth time is what makes this specific to you, not just anyone born that day.
        </div>

        {/* Name + Email row */}
        <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:12, marginBottom:16 }}>
          <div>
            <label style={lbl}>First name</label>
            <input value={fname} onChange={e=>setFname(e.target.value)} placeholder="e.g. Sarah" style={inp}/>
          </div>
          <div>
            <label style={lbl}>Email address</label>
            <input type="email" value={email} onChange={e=>setEmail(e.target.value)}
              placeholder="you@email.com" style={inp}/>
            <small style={{ fontSize:11, color:"#3a3858", marginTop:4, display:"block" }}>
              Your reading is sent here after payment
            </small>
          </div>
        </div>

        {/* DOB + Time row */}
        <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:12, marginBottom:16 }}>
          <div>
            <label style={lbl}>Date of birth</label>
            <input type="date" value={dob} onChange={e=>setDob(e.target.value)} style={inp}/>
          </div>
          <div>
            <label style={lbl}>Time of birth</label>
            <input type="time" value={btime} onChange={e=>setBtime(e.target.value)} style={inp}/>
            <small style={{ fontSize:11, color:"#3a3858", marginTop:4, display:"block" }}>
              From birth certificate
            </small>
          </div>
        </div>

        {/* City */}
        <div style={{ marginBottom:24 }}>
          <label style={lbl}>City &amp; country of birth</label>
          <input value={city} onChange={e=>setCity(e.target.value)}
            placeholder="e.g. New York, USA or London, UK" style={inp}/>
        </div>

        <button onClick={submit} style={{ width:"100%",
          background:"linear-gradient(135deg,#6b2fd4,#d4537e)", color:"#fff", border:"none",
          borderRadius:12, padding:"16px 20px", fontSize:15, fontWeight:600,
          fontFamily:"inherit", cursor:"pointer", letterSpacing:"0.2px" }}>
          Read my chart — free preview ✨
        </button>
      </div>
      <div style={{ fontSize:11, color:"#2e2c3e", textAlign:"center", marginTop:14 }}>
        For entertainment purposes only · Not professional advice
      </div>
    </div>
  );

  // ── LOADING ──────────────────────────────────────────────────────────────────
  if (screen === "loading") return (
    <div style={{ textAlign:"center", padding:"80px 0" }}>
      <span style={{ fontSize:60, display:"block", animation:"bob 1.8s ease-in-out infinite" }}>🌙</span>
      <div style={{ fontFamily:"var(--font-display)", fontSize:22, margin:"16px 0 8px", color:"#e8e4f0" }}>
        {loadMsg}
      </div>
      <div style={{ fontSize:13, color:"#4a4560" }}>Calculating your planetary positions…</div>
    </div>
  );

  // ── RESULT ───────────────────────────────────────────────────────────────────
  if (screen === "result" && data) {
    const { planets, preview, shareCard } = data;

    return (
      <div style={{ maxWidth:800, margin:"0 auto" }}>

        {/* ── NATAL CHART WHEEL ── */}
        <div style={{ background:"linear-gradient(160deg,rgba(107,47,212,0.08) 0%,rgba(10,4,24,0.7) 100%)",
          border:"1px solid rgba(107,47,212,0.18)", borderRadius:24, marginBottom:48, overflow:"hidden" }}>
          <div style={{ borderBottom:"0.5px solid rgba(107,47,212,0.12)", padding:"22px 32px 18px",
            display:"flex", alignItems:"center", gap:10 }}>
            <div style={{ width:6, height:6, borderRadius:"50%",
              background:"linear-gradient(135deg,#9b6fe8,#d4537e)", flexShrink:0 }}/>
            <div style={{ fontSize:11, fontWeight:700, letterSpacing:"2px",
              textTransform:"uppercase" as const, color:"rgba(155,111,232,0.7)" }}>
              Natal Chart · Swiss Ephemeris
            </div>
            <div style={{ flex:1 }}/>
            <div style={{ fontSize:12, color:"rgba(232,228,240,0.3)" }}>{fname}</div>
          </div>
          <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr",
            gap:0, padding:"36px 32px 32px", alignItems:"center" }}>
            <div>
              <BirthChartWheel planets={planets} name={fname}/>
            </div>
            <div style={{ paddingLeft:28 }}>
              <div style={{ fontSize:10, fontWeight:700, letterSpacing:"2px",
                textTransform:"uppercase" as const, color:"rgba(232,228,240,0.25)", marginBottom:20 }}>
                Planetary Positions
              </div>
              <div style={{ display:"flex", flexDirection:"column" }}>
                {PLANET_ORDER.filter(k => planets[k as keyof PlanetMap]).map(k => (
                  <div key={k} style={{ display:"flex", alignItems:"center", gap:10,
                    padding:"10px 0", borderBottom:"0.5px solid rgba(255,255,255,0.04)" }}>
                    <div style={{ width:8, height:8, borderRadius:"50%",
                      background:DOT_COLORS[k], flexShrink:0,
                      boxShadow:`0 0 8px ${DOT_COLORS[k]}60` }}/>
                    <span style={{ fontSize:12, color:"rgba(232,228,240,0.35)", minWidth:64 }}>
                      {PLANET_LABELS[k]}
                    </span>
                    <span style={{ fontSize:13, color:"rgba(232,228,240,0.82)", fontWeight:500 }}>
                      {planets[k as keyof PlanetMap]}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* ── FREE PREVIEW — 2 insights ── */}
        <SectionDivider label="Free preview · 2 insights" />
        {preview.slice(0,2).map((ins, i) => (
          <InsightCard key={i} ins={ins} badge="Free" badgeColor="teal"/>
        ))}

        {/* ── SHARE CARD — shown free for virality ── */}
        <div style={{ marginTop:48, marginBottom:48 }}>
          <SectionDivider label="Your shareable identity card" />
          <p style={{ textAlign:"center", fontSize:14, color:"rgba(232,228,240,0.45)",
            marginBottom:24, fontFamily:"var(--font-display)", fontStyle:"italic" }}>
            Your chart just exposed you. Post it. Send it. Let them figure out who it&apos;s about.
          </p>
          <ViralShareCard fname={fname} shareCard={shareCard}/>
          <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr 1fr", gap:12, marginTop:18 }}>
            <button onClick={handleShare}
              style={{ background:"linear-gradient(135deg,#d4537e,#6b2fd4)", border:"none",
                borderRadius:12, padding:"15px 16px", fontSize:13, fontWeight:600,
                fontFamily:"inherit", color:"#fff", cursor:"pointer" }}>
              {shareLbl}
            </button>
            <button onClick={handleDownload} disabled={downloading}
              style={{ background:"linear-gradient(135deg,#6b2fd4,#9b4fd4)", border:"none",
                borderRadius:12, padding:"15px 16px", fontSize:13, fontWeight:600,
                fontFamily:"inherit", color:"#fff",
                cursor:downloading?"not-allowed":"pointer", opacity:downloading?0.65:1 }}>
              {dlLbl}
            </button>
            <button onClick={() => copyQuote(shareCard.quote)}
              style={{ background:"transparent", border:"0.5px solid rgba(255,255,255,0.12)",
                borderRadius:12, padding:"15px 16px", fontSize:13, fontWeight:500,
                fontFamily:"inherit", color:"#e8e4f0", cursor:"pointer" }}>
              {copyLbl}
            </button>
          </div>
          <div style={{ fontSize:11, color:"#252340", textAlign:"center", marginTop:10 }}>
            Download saves a 1080px PNG · perfect for Stories, Reels &amp; Snapchat
          </div>
        </div>

        {/* ── LOCK WALL ── */}
        <div style={{ background:"rgba(255,255,255,0.02)", border:"0.5px solid rgba(255,255,255,0.06)",
          borderRadius:20, overflow:"hidden", marginBottom:28 }}>
          <div style={{ padding:"8px 0", position:"relative" }}>
            {LOCKED_TEASERS.map((l, i) => (
              <div key={i} style={{ display:"flex", alignItems:"flex-start", gap:12,
                padding:"14px 28px",
                borderBottom: i < LOCKED_TEASERS.length-1 ? "0.5px solid rgba(255,255,255,0.05)" : "none",
                filter: i >= 4 ? "blur(3px)" : "none" }}>
                <div style={{ width:7, height:7, borderRadius:"50%",
                  background:"rgba(107,47,212,0.45)", flexShrink:0, marginTop:4 }}/>
                <div style={{ fontSize:13, color:"rgba(232,228,240,0.45)", flex:1, lineHeight:1.55 }}>
                  {l}
                </div>
                <span style={{ fontSize:13, color:"rgba(155,111,232,0.35)", flexShrink:0 }}>🔒</span>
              </div>
            ))}
            <div style={{ position:"absolute", bottom:0, left:0, right:0, height:80,
              background:"linear-gradient(to bottom,transparent,rgba(9,9,15,0.9))", pointerEvents:"none" }}/>
          </div>
          <div style={{ background:"rgba(107,47,212,0.04)", borderTop:"0.5px solid rgba(107,47,212,0.1)",
            padding:"32px 28px 28px", textAlign:"center" }}>
            <div style={{ fontFamily:"var(--font-display)", fontSize:20, marginBottom:10, color:"#e8e4f0" }}>
              8 more insights waiting
            </div>
            <p style={{ fontSize:14, color:"#6b6585", lineHeight:1.75, maxWidth:380,
              margin:"0 auto 24px" }}>
              Venus retrograde truth. Your self-sabotage pattern named. The 12th house shadow.
              Delivered to your email the moment you pay. Yours forever.
            </p>
            <button onClick={handleUnlock}
              style={{ display:"block", width:"100%",
                background:"linear-gradient(135deg,#f0b84a,#e8854a)",
                color:"#0d0800", border:"none", borderRadius:12, padding:"17px 20px",
                fontSize:15, fontWeight:700, fontFamily:"inherit", cursor:"pointer",
                letterSpacing:"0.2px" }}>
              Unlock full reading · $15 ✦
            </button>
            <div style={{ fontSize:11, color:"#3a3858", marginTop:10 }}>
              One-time · No subscription · Full reading emailed instantly after payment
            </div>
          </div>
        </div>

        <button onClick={reset} style={{ width:"100%", background:"transparent", border:"none",
          padding:"18px", fontSize:13, color:"#4a4560", cursor:"pointer", fontFamily:"inherit", marginTop:8 }}>
          ← Read a different chart
        </button>
        <div style={{ fontSize:11, color:"#2a2840", textAlign:"center", marginTop:4, lineHeight:1.5 }}>
          For entertainment purposes only · Not psychological or medical advice
        </div>
      </div>
    );
  }
  return null;
}

// ─── FAQ ───────────────────────────────────────────────────────────────────────

function FAQ() {
  const [open, setOpen] = useState<number|null>(null);
  return (
    <div style={{ marginTop:48, maxWidth:720, margin:"48px auto 0" }}>
      {FAQS.map((f, i) => (
        <div key={i} style={{ borderBottom:"0.5px solid rgba(255,255,255,0.08)" }}>
          <button onClick={() => setOpen(p => p===i ? null : i)}
            style={{ width:"100%", background:"transparent", border:"none", padding:"22px 0",
              display:"flex", alignItems:"center", justifyContent:"space-between", gap:16,
              cursor:"pointer", fontFamily:"inherit", textAlign:"left" }}>
            <span style={{ fontSize:"0.97rem", fontWeight:600, color:"#e8e4f0", lineHeight:1.45, flex:1 }}>
              {f.q}
            </span>
            <span style={{ width:26, height:26, borderRadius:"50%",
              border:"0.5px solid rgba(255,255,255,0.12)", display:"flex", alignItems:"center",
              justifyContent:"center", flexShrink:0, fontSize:14, color:"#6b2fd4", fontWeight:700,
              background:open===i?"rgba(107,47,212,0.12)":"transparent", transition:"all .2s" }}>
              {open===i?"−":"+"}
            </span>
          </button>
          <div style={{ maxHeight:open===i?400:0, overflow:"hidden",
            transition:"max-height .35s cubic-bezier(.4,0,.2,1)" }}>
            <p style={{ fontSize:"0.89rem", color:"rgba(232,228,240,0.65)",
              lineHeight:1.78, paddingBottom:22, paddingRight:40 }}>{f.a}</p>
          </div>
        </div>
      ))}
    </div>
  );
}

// ─── PAGE ──────────────────────────────────────────────────────────────────────

export default function HomePage() {
  const [wlName,    setWlName]    = useState("");
  const [wlEmail,   setWlEmail]   = useState("");
  const [reason,    setReason]    = useState("Compatibility Reading");
  const [submitted, setSubmitted] = useState(false);
  const [wlLoading, setWlLoading] = useState(false);
  const [scrolled,  setScrolled]  = useState(false);
  const [resultShowing, setResultShowing] = useState(false);

  useEffect(() => {
    const fn = () => setScrolled(window.scrollY > 40);
    window.addEventListener("scroll", fn, { passive:true });
    return () => window.removeEventListener("scroll", fn);
  }, []);

  const handleWaitlist = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!wlName || !wlEmail) return;
    setWlLoading(true);
    try {
      await fetch(
        "https://script.google.com/macros/s/AKfycbwgxIPG-QmNI89GEMqeV6GA83STXCncvc77fsqH6bAK3AatSO3pfi96TzGNSB6ZvxGIMA/exec",
        { method:"POST", mode:"no-cors", headers:{"Content-Type":"application/json"},
          body:JSON.stringify({ name:wlName, email:wlEmail, reason, source:"Website Waitlist" }) }
      );
      setSubmitted(true); setWlName(""); setWlEmail(""); setReason("Compatibility Reading");
    } catch { alert("Something went wrong."); }
    setWlLoading(false);
  };

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;0,900;1,400;1,700&family=DM+Sans:wght@300;400;500;600&display=swap');
        *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
        :root{
          --font-display:'Playfair Display',Georgia,serif;
          --font-body:'DM Sans',system-ui,sans-serif;
          --bg:#09090f;--card:#12121e;
          --border:rgba(255,255,255,0.08);--border2:rgba(255,255,255,0.12);
          --white:#e8e4f0;--dim:rgba(232,228,240,0.55);--faint:rgba(232,228,240,0.08);
          --gold:#F0B84A;--gold-dim:rgba(240,184,74,0.18);
          --purple:#6b2fd4;--rose:#d4537e;--teal:#5dcaa5;
        }
        html{scroll-behavior:smooth}
        body{background:var(--bg);color:var(--white);font-family:var(--font-body);font-size:16px;line-height:1.6;-webkit-font-smoothing:antialiased;overflow-x:hidden}
        @keyframes bob{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}
        @keyframes fadeUp{from{opacity:0;transform:translateY(22px)}to{opacity:1;transform:translateY(0)}}
        @keyframes pulse{0%,100%{opacity:.5;transform:translate(-50%,-55%) scale(1)}50%{opacity:1;transform:translate(-50%,-55%) scale(1.03)}}
        @keyframes blink{0%,100%{opacity:1}50%{opacity:.3}}
        .c{max-width:1100px;margin:0 auto;padding:0 24px}
        section{position:relative;z-index:1}
        .nav{position:fixed;top:0;left:0;right:0;z-index:100;padding:18px 0;transition:all .3s}
        .nav.on{background:rgba(9,9,15,.92);border-bottom:1px solid var(--border);backdrop-filter:blur(16px)}
        .nav-i{display:flex;align-items:center;justify-content:space-between}
        .logo{font-family:var(--font-display);font-size:1.3rem;font-weight:700;text-decoration:none;letter-spacing:.02em}
        .logo .g{background:linear-gradient(135deg,#f0b84a,#d4537e,#6b2fd4);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
        .nl{display:flex;align-items:center;gap:28px;list-style:none}
        .nl a{font-size:.83rem;font-weight:500;color:var(--dim);text-decoration:none;letter-spacing:.04em;text-transform:uppercase;transition:color .2s}
        .nl a:hover{color:var(--white)}
        .ncta{color:var(--gold)!important;border:1px solid var(--gold-dim);padding:6px 15px;border-radius:4px}
        .ncta:hover{background:var(--gold-dim)}
        .hero{min-height:100vh;display:flex;align-items:center;padding-top:96px;padding-bottom:80px;overflow:hidden}
        .hbg{position:absolute;inset:0;background:radial-gradient(ellipse 80% 60% at 50% -10%,rgba(107,47,212,.1) 0%,transparent 50%),radial-gradient(ellipse 40% 40% at 85% 60%,rgba(212,83,126,.06) 0%,transparent 60%);pointer-events:none}
        .horb{position:absolute;top:50%;left:50%;transform:translate(-50%,-55%);width:560px;height:560px;border-radius:50%;border:1px solid rgba(107,47,212,.08);background:radial-gradient(circle,rgba(107,47,212,.04) 0%,transparent 50%);animation:pulse 8s ease-in-out infinite;pointer-events:none}
        .hi{position:relative;z-index:1;text-align:center;max-width:860px;margin:0 auto}
        .ey{display:inline-flex;align-items:center;gap:8px;font-size:.73rem;font-weight:700;letter-spacing:.14em;text-transform:uppercase;color:var(--gold);margin-bottom:28px;padding:5px 14px;border:1px solid var(--gold-dim);border-radius:100px;background:rgba(240,184,74,.06);animation:fadeUp .6s ease both}
        h1{font-family:var(--font-display);font-size:clamp(2.8rem,7vw,5.2rem);font-weight:900;line-height:1.06;letter-spacing:-.02em;animation:fadeUp .6s .1s ease both}
        h1 em{font-style:italic;background:linear-gradient(135deg,#f0b84a,#d4537e);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
        .hsh{font-family:var(--font-display);font-size:clamp(1.3rem,2.8vw,1.8rem);font-style:italic;color:var(--dim);margin:10px 0 18px;animation:fadeUp .6s .15s ease both}
        .hb{font-size:1.05rem;color:var(--dim);max-width:540px;margin:0 auto 36px;line-height:1.72;animation:fadeUp .6s .2s ease both}
        .hctas{display:flex;align-items:center;justify-content:center;gap:14px;flex-wrap:wrap;animation:fadeUp .6s .25s ease both}
        .htr{margin-top:44px;display:flex;align-items:center;justify-content:center;gap:18px;flex-wrap:wrap;animation:fadeUp .6s .3s ease both;font-size:.82rem;color:var(--dim)}
        .htr strong{color:var(--white)}
        .dot{width:3px;height:3px;border-radius:50%;background:rgba(240,184,74,.3)}
        .bp{display:inline-flex;align-items:center;gap:8px;padding:14px 30px;background:linear-gradient(135deg,#6b2fd4,#d4537e);color:#fff;font-family:inherit;font-size:.88rem;font-weight:700;letter-spacing:.04em;text-transform:uppercase;text-decoration:none;border:none;border-radius:10px;cursor:pointer;transition:opacity .2s,transform .15s}
        .bp:hover{opacity:.88;transform:translateY(-1px)}
        .bs{display:inline-flex;align-items:center;gap:8px;padding:14px 30px;background:transparent;color:var(--white);font-family:inherit;font-size:.88rem;font-weight:600;letter-spacing:.04em;text-transform:uppercase;text-decoration:none;border:1px solid var(--border2);border-radius:10px;cursor:pointer;transition:all .2s}
        .bs:hover{border-color:rgba(255,255,255,.22);background:var(--faint);transform:translateY(-1px)}
        .sec{padding:96px 0}
        .dk{background:#0d0d18;border-top:1px solid var(--border);border-bottom:1px solid var(--border)}
        .sl{display:flex;align-items:center;gap:10px;margin-bottom:14px}
        .sl::before{content:'';display:block;width:22px;height:1px;background:var(--gold)}
        .sl span{font-size:.7rem;font-weight:700;letter-spacing:.16em;text-transform:uppercase;color:var(--gold)}
        h2{font-family:var(--font-display);font-size:clamp(2rem,4.5vw,3.1rem);font-weight:800;line-height:1.1;letter-spacing:-.02em;margin-bottom:12px}
        h2 em{font-style:italic;background:linear-gradient(135deg,#f0b84a,#d4537e);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
        .sub{font-size:1rem;color:var(--dim);max-width:500px;line-height:1.72}
        .try-sec{padding:96px 0}
        .cred-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:36px;max-width:800px}
        .cred-item{display:flex;align-items:center;gap:12px;padding:14px 16px;background:var(--card);border:0.5px solid var(--border);border-radius:12px;transition:border-color .2s}
        .cred-item:hover{border-color:rgba(107,47,212,.3)}
        .cred-icon{font-size:18px;width:28px;text-align:center;flex-shrink:0;color:var(--gold);font-family:serif}
        .cred-label{font-size:12px;font-weight:700;color:var(--white);letter-spacing:.03em;margin-bottom:1px}
        .cred-desc{font-size:11px;color:rgba(232,228,240,.35)}
        .form-wrap{margin-top:64px;padding-top:56px;border-top:0.5px solid rgba(255,255,255,0.06)}
        .rg{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--border);border:1px solid var(--border);border-radius:14px;overflow:hidden;margin-top:48px}
        .ri{background:var(--card);padding:30px;transition:background .2s}
        .ri:hover{background:#1a1a2e}
        .rn{font-family:var(--font-display);font-size:2.2rem;font-weight:900;color:rgba(107,47,212,.22);line-height:1;margin-bottom:10px}
        .rt{font-size:.93rem;font-weight:600;margin-bottom:8px}
        .rb{font-size:.83rem;color:var(--dim);line-height:1.65}
        .price-main{background:linear-gradient(135deg,var(--card) 0%,rgba(107,47,212,.08) 100%);border:1px solid rgba(240,184,74,.4);border-radius:18px;padding:36px 32px;position:relative;overflow:hidden}
        .price-main::before{content:'';position:absolute;inset:0;background:radial-gradient(ellipse 80% 60% at 50% 0%,rgba(107,47,212,.06) 0%,transparent 60%);pointer-events:none}
        .price-badge-main{display:inline-block;font-size:.65rem;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:#1a0a00;background:var(--gold);padding:4px 12px;border-radius:100px;margin-bottom:18px}
        .price-title{font-family:var(--font-display);font-size:1.6rem;font-weight:800;margin-bottom:12px;color:var(--white)}
        .price-desc{font-size:.9rem;color:var(--dim);line-height:1.72;margin-bottom:24px}
        .price-num{font-family:var(--font-display);font-size:3rem;font-weight:900;color:var(--gold);line-height:1}
        .price-sub{font-size:.8rem;color:rgba(232,228,240,.35);margin-top:4px;margin-bottom:28px}
        .price-includes{list-style:none;display:flex;flex-direction:column;gap:9px;margin-bottom:28px}
        .price-includes li{font-size:.86rem;color:var(--dim);display:flex;align-items:center;gap:10px}
        .price-includes li::before{content:'✓';color:var(--teal);font-weight:700;flex-shrink:0}
        .upcoming-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:32px}
        .uc{background:var(--card);border:0.5px solid var(--border);border-radius:14px;padding:26px 22px;display:flex;flex-direction:column;position:relative;overflow:hidden}
        .uc::after{content:'';position:absolute;inset:0;background:rgba(9,9,15,.35);pointer-events:none}
        .uc-badge{display:inline-block;font-size:.62rem;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:#4a4560;background:rgba(255,255,255,.05);padding:3px 10px;border-radius:100px;margin-bottom:14px;width:fit-content}
        .uc-title{font-family:var(--font-display);font-size:1.1rem;font-weight:700;margin-bottom:8px;color:rgba(232,228,240,.5)}
        .uc-desc{font-size:.82rem;color:rgba(232,228,240,.28);line-height:1.65;flex:1;margin-bottom:18px}
        .uc-price{font-family:var(--font-display);font-size:1.6rem;font-weight:900;color:#2e2c3e}
        .uc-soon{display:inline-block;font-size:.72rem;font-weight:600;color:#4a4560;border:0.5px solid rgba(255,255,255,.08);border-radius:6px;padding:4px 12px;margin-top:10px}
        .cmp-wrap{margin-top:48px;border:1px solid var(--border);border-radius:16px;overflow:hidden}
        .cmp-head{display:grid;grid-template-columns:1fr 140px 140px;background:#0d0d18;border-bottom:1px solid var(--border)}
        .cmp-head-cell{padding:16px 20px;font-size:.72rem;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:var(--dim)}
        .cmp-head-cell.hl{color:var(--gold)}
        .cmp-row{display:grid;grid-template-columns:1fr 140px 140px;border-bottom:0.5px solid rgba(255,255,255,.05);transition:background .15s}
        .cmp-row:last-child{border-bottom:none}
        .cmp-row:hover{background:rgba(107,47,212,.04)}
        .cmp-cell{padding:15px 20px;font-size:.88rem;color:var(--dim);display:flex;align-items:center}
        .cmp-cell.feat{color:var(--white);font-weight:500}
        .cmp-yes{color:var(--teal);font-size:1rem}
        .cmp-no{color:rgba(212,83,126,.6);font-size:.82rem}
        .cmp-partial{color:#6b6585;font-size:.82rem;font-style:italic}
        .cmp-sub{color:rgba(212,83,126,.7);font-size:.82rem;font-style:italic}
        .cmp-cta{text-align:center;padding:28px;background:#0d0d18;border-top:1px solid var(--border)}
        .revg{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:18px;margin-top:48px}
        .revc{background:var(--card);border:0.5px solid var(--border);border-radius:14px;padding:26px;transition:border-color .2s,transform .2s;position:relative;overflow:hidden}
        .revc::before{content:'"';position:absolute;top:-12px;right:18px;font-family:var(--font-display);font-size:5rem;color:rgba(107,47,212,.1);line-height:1;pointer-events:none}
        .revc:hover{border-color:rgba(107,47,212,.3);transform:translateY(-2px)}
        .revt{font-size:.91rem;color:var(--white);line-height:1.68;margin-bottom:18px;font-style:italic}
        .reva{display:flex;align-items:center;gap:10px}
        .revav{width:34px;height:34px;border-radius:50%;background:linear-gradient(135deg,#6b2fd4,#d4537e);display:flex;align-items:center;justify-content:center;font-family:var(--font-display);font-size:.9rem;font-weight:700;color:#fff;flex-shrink:0}
        .revn{font-size:.83rem;font-weight:600;color:var(--dim)}
        .revm{font-size:.73rem;color:rgba(232,228,240,.3)}
        .waitlist-sec{padding:96px 0;position:relative;overflow:hidden;background:#0d0d18;border-top:1px solid var(--border)}
        .wbg{position:absolute;inset:0;background:radial-gradient(ellipse 50% 50% at 50% 50%,rgba(107,47,212,.05) 0%,transparent 50%);pointer-events:none}
        .wi{position:relative;z-index:1;max-width:600px;margin:0 auto;text-align:center}
        .ei{width:100%;background:var(--faint);border:0.5px solid var(--border);border-radius:10px;padding:13px 16px;color:var(--white);font-family:inherit;font-size:.88rem;outline:none;transition:border-color .2s}
        .ei:focus{border-color:rgba(107,47,212,.5)}
        .ei::placeholder{color:rgba(232,228,240,.25)}
        .fn{font-size:.76rem;color:rgba(232,228,240,.28)}
        .fs{padding:14px 22px;background:rgba(93,202,165,.1);border:0.5px solid rgba(93,202,165,.3);border-radius:10px;color:var(--teal);font-size:.88rem;font-weight:500;max-width:420px;margin:0 auto}
        .wl-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:40px}
        .wl-card{background:var(--card);border:0.5px solid var(--border);border-radius:12px;padding:20px 18px;text-align:left}
        .wl-card-badge{font-size:.6rem;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:#4a4560;margin-bottom:8px}
        .wl-card-title{font-family:var(--font-display);font-size:1rem;font-weight:700;color:rgba(232,228,240,.55);margin-bottom:6px}
        .wl-card-price{font-family:var(--font-display);font-size:1.4rem;font-weight:900;color:#2e2c3e}
        .footer{border-top:1px solid var(--border);padding:48px 0 30px;position:relative;z-index:1}
        .fi{display:flex;align-items:flex-start;justify-content:space-between;gap:36px;flex-wrap:wrap;margin-bottom:36px}
        .fb p{font-size:.82rem;color:var(--dim);max-width:240px;line-height:1.6;margin-top:8px}
        .fl h4{font-size:.7rem;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:var(--dim);margin-bottom:14px}
        .fl ul{list-style:none;display:flex;flex-direction:column;gap:10px}
        .fl a{font-size:.83rem;color:rgba(232,228,240,.35);text-decoration:none;transition:color .2s}
        .fl a:hover{color:var(--white)}
        .slinks{display:flex;gap:10px;margin-top:14px}
        .sl2{display:flex;align-items:center;justify-content:center;width:36px;height:36px;border:0.5px solid var(--border);border-radius:8px;color:var(--dim);text-decoration:none;font-size:.82rem;font-weight:700;transition:all .2s}
        .sl2:hover{border-color:rgba(107,47,212,.4);color:var(--gold);background:rgba(107,47,212,.1)}
        .fb2{border-top:1px solid var(--border);padding-top:22px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px}
        .disc{font-size:.73rem;color:rgba(232,228,240,.25);max-width:520px;line-height:1.55}
        .copy{font-size:.73rem;color:rgba(232,228,240,.2)}
        @media(max-width:900px){.cred-grid{grid-template-columns:1fr 1fr}.upcoming-grid,.wl-cards{grid-template-columns:1fr}.cmp-head,.cmp-row{grid-template-columns:1fr 110px 110px}}
        @media(max-width:768px){.nl{display:none}.hero{padding-top:90px;padding-bottom:64px}.horb{width:300px;height:300px}.hctas{flex-direction:column;align-items:center}.bp,.bs{width:100%;max-width:300px;justify-content:center}.htr{flex-direction:column;gap:10px}.rg{grid-template-columns:1fr}.fi{flex-direction:column;gap:28px}.fb2{flex-direction:column;align-items:flex-start}.revg{grid-template-columns:1fr}.cmp-head,.cmp-row{grid-template-columns:1fr 90px 90px}.cred-grid{grid-template-columns:1fr}}
        @media(max-width:480px){.sec,.try-sec,.waitlist-sec{padding:72px 0}.c{padding:0 16px}.price-main{padding:24px 20px}.upcoming-grid,.wl-cards{grid-template-columns:1fr}}
      `}</style>

      {/* NAV */}
      <nav className={`nav${scrolled?" on":""}`}>
        <div className="c nav-i">
          <a className="logo" href="#" style={{ display:"flex", alignItems:"center", gap:10 }}>
            <Image src="/mascot.png" alt="BluntChart mascot" width={34} height={34} style={{ borderRadius:"50%" }}/>
            <span className="g">BluntChart</span>
          </a>
          <ul className="nl">
            <li><a href="#try-it">Try Free</a></li>
            <li><a href="#reveals">What We Reveal</a></li>
            <li><a href="#reviews">Reviews</a></li>
            <li><a href="#compare">vs Co-Star</a></li>
            <li><a className="ncta" href="#try-it">Get Reading $15</a></li>
          </ul>
        </div>
      </nav>

      {/* ── HERO ── */}
      <section className="hero">
        <div className="hbg"/><div className="horb"/>
        <div className="c">
          <div className="hi">
            <div style={{ marginBottom:24 }}>
              <Image src="/mascot.png" alt="BluntChart cosmic cat mascot" width={130} height={130} priority
                style={{ margin:"0 auto", filter:"drop-shadow(0 0 30px rgba(107,47,212,.35))" }}/>
            </div>
            <div className="ey">✦ Brutally honest birth chart readings</div>
            <h1>Your chart already knows<br/><em>why you&apos;re like this.</em></h1>
            <p className="hsh">It&apos;s time you did too.</p>
            <p className="hb">BluntChart takes your birth date, time, and place. Calculates your real natal chart and delivers a reading that tells you the truth in plain language, no sugarcoating.</p>
            <div className="hctas">
              <a className="bp" href="#try-it">Get My Free Preview ✨</a>
              <a className="bs" href="#reveals">See What We Reveal ↓</a>
            </div>
            <div className="htr">
              <span><strong>$15</strong>&nbsp;one-time. No subscription.</span>
              <span className="dot"/>
              <span>Real chart calculation</span>
              <span className="dot"/>
              <span>~1,500 words specific to <em>your</em> chart</span>
            </div>
          </div>
        </div>
      </section>

      {/* ── TRY IT ── */}
      <section className="try-sec" id="try-it">
        <div className="c">
          {!resultShowing && (
            <>
              <div className="sl"><span>Real natal chart · Swiss Ephemeris</span></div>
              <h2 style={{ maxWidth:640 }}>Two answers,<br/><em>completely free.</em></h2>
              <p className="sub">No account. No payment. Enter your birth details and we&apos;ll tell you what your chart actually says. Not your sign. <em>Your chart.</em></p>
              <div className="cred-grid">
                {PLANET_CREDENTIALS.map((item, i) => (
                  <div className="cred-item" key={i}>
                    <span className="cred-icon">{item.icon}</span>
                    <div>
                      <div className="cred-label">{item.label}</div>
                      <div className="cred-desc">{item.desc}</div>
                    </div>
                  </div>
                ))}
              </div>
              <div style={{ display:"flex", alignItems:"center", gap:20, marginTop:28, padding:"14px 20px",
                background:"var(--card)", border:"0.5px solid var(--border)", borderRadius:12,
                maxWidth:800, flexWrap:"wrap" }}>
                {["No account needed","Real chart calculation","Instant result","Full reading emailed after payment"].map((t,i) => (
                  <span key={i} style={{ fontSize:12, color:"rgba(232,228,240,0.45)", display:"flex", alignItems:"center", gap:6 }}>
                    <span style={{ color:"#5dcaa5", fontWeight:700 }}>✓</span>{t}
                  </span>
                ))}
              </div>
            </>
          )}
          <div className="form-wrap" style={resultShowing ? { borderTop:"none", marginTop:0, paddingTop:0 } : {}}>
            {!resultShowing && (
              <div style={{ textAlign:"center", marginBottom:40 }}>
                <div style={{ fontFamily:"var(--font-display)", fontSize:"clamp(1.4rem,3vw,2rem)",
                  fontWeight:700, color:"#e8e4f0", marginBottom:8 }}>
                  Enter your birth details below
                </div>
                <p style={{ fontSize:14, color:"#6b6585", maxWidth:480, margin:"0 auto" }}>
                  Your email is where we send your full reading after payment.
                </p>
              </div>
            )}
            <ReadingApp onResultChange={setResultShowing}/>
          </div>
        </div>
      </section>

      {/* ── WHAT WE REVEAL ── */}
      <section className="sec dk" id="reveals">
        <div className="c">
          <div className="sl"><span>What we actually say</span></div>
          <h2>The parts other apps<br/><em>won&apos;t touch.</em></h2>
          <p className="sub">Generic readings tell you you&apos;re creative and sensitive. We tell you why you text back immediately and then resent yourself for it.</p>
          <div className="rg">
            {REVEALS.map(r => (
              <div className="ri" key={r.num}>
                <div className="rn">{r.num}</div>
                <div className="rt">{r.title}</div>
                <div className="rb">{r.body}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── PRICING ── */}
      <section className="sec" id="readings">
        <div className="c">
          <div className="sl"><span>Readings</span></div>
          <h2>One-time. No subscription.<br/><em>No trap.</em></h2>
          <p className="sub">Pay once, get your reading. Delivered to your email instantly, yours forever.</p>
          <div className="price-main" style={{ maxWidth:560, marginTop:48 }}>
            <div style={{ position:"relative", zIndex:1 }}>
              <div className="price-badge-main">⭐ Most Popular</div>
              <div className="price-title">Full Birth Chart Reading</div>
              <p className="price-desc">10 brutally honest insights across all your planets, houses, and key life areas. Emailed to you the moment payment goes through.</p>
              <div className="price-num">$15</div>
              <p className="price-sub">One-time · Emailed instantly · Yours forever</p>
              <ul className="price-includes">
                <li>2 free insights before you pay</li>
                <li>8 deeper paid insights emailed after payment</li>
                <li>Shareable viral identity card (download free)</li>
                <li>Real Swiss Ephemeris calculations</li>
                <li>No account required</li>
              </ul>
              <a className="bp" href="#try-it" style={{ display:"block", textAlign:"center", textDecoration:"none" }}>
                Get My Free Preview First ✨
              </a>
            </div>
          </div>
          <div style={{ marginTop:56 }}>
            <div style={{ display:"flex", alignItems:"center", gap:10, marginBottom:24 }}>
              <div style={{ width:22, height:1, background:"rgba(255,255,255,.15)" }}/>
              <span style={{ fontSize:".7rem", fontWeight:700, letterSpacing:".16em",
                textTransform:"uppercase" as const, color:"#4a4560" }}>
                More readings coming
              </span>
            </div>
            <div className="upcoming-grid">
              {UPCOMING.map(u => (
                <div className="uc" key={u.title}>
                  <div className="uc-badge">{u.badge}</div>
                  <div className="uc-title">{u.title}</div>
                  <p className="uc-desc">{u.desc}</p>
                  <div className="uc-price">{u.price}</div>
                  <div className="uc-soon">Launching Soon</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── REVIEWS ── */}
      <section className="sec dk" id="reviews">
        <div className="c">
          <div className="sl"><span>Beta reader reactions</span></div>
          <h2>People keep sending it<br/><em>to their friends.</em></h2>
          <p className="sub">Real responses from our closed beta. Unfiltered, because that&apos;s the whole point.</p>
          <div className="revg">
            {REVIEWS.map(r => (
              <div className="revc" key={r.name}>
                <div style={{ display:"flex", gap:2, marginBottom:12 }}>
                  {Array.from({length:5}).map((_,i) => <span key={i} style={{ color:"#F0B84A", fontSize:13 }}>★</span>)}
                </div>
                <p className="revt">&ldquo;{r.text}&rdquo;</p>
                <div className="reva">
                  <div className="revav">{r.init}</div>
                  <div>
                    <div className="revn">{r.name}</div>
                    <div className="revm">{r.meta}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── COMPARISON ── */}
      <section className="sec" id="compare">
        <div className="c">
          <div className="sl"><span>Co-Star alternative</span></div>
          <h2>Why people are<br/><em>leaving Co&#8209;Star.</em></h2>
          <p className="sub">Less vague quotes. More specific truths.</p>
          <div className="cmp-wrap">
            <div className="cmp-head">
              <div className="cmp-head-cell">Feature</div>
              <div className="cmp-head-cell hl">BluntChart</div>
              <div className="cmp-head-cell">Co&#8209;Star</div>
            </div>
            {COMPARISON.map((row, i) => (
              <div className="cmp-row" key={i}>
                <div className="cmp-cell feat">{row.feature}</div>
                <div className="cmp-cell">
                  {row.us === true ? <span className="cmp-yes">✓</span> : <span className="cmp-no">✗</span>}
                </div>
                <div className="cmp-cell">
                  {row.them === true  ? <span className="cmp-yes">✓</span>
                   : row.them === false ? <span className="cmp-no">✗</span>
                   : row.them === "Subscription" ? <span className="cmp-sub">Subscription</span>
                   : <span className="cmp-partial">{row.them}</span>}
                </div>
              </div>
            ))}
            <div className="cmp-cta">
              <p style={{ fontSize:".87rem", color:"var(--dim)", marginBottom:16, maxWidth:440, margin:"0 auto 18px" }}>
                Co-Star is built for daily engagement. BluntChart is built for one honest conversation with your chart.
              </p>
              <a className="bp" href="#try-it" style={{ textDecoration:"none", display:"inline-flex" }}>
                Try BluntChart Free ✨
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* ── FAQ ── */}
      <section className="sec dk">
        <div className="c">
          <div className="sl"><span>Common questions</span></div>
          <h2>Everything you&apos;re<br/><em>wondering about.</em></h2>
          <p className="sub">The questions people ask before they get their reading and after they realise it was more accurate than they expected.</p>
          <FAQ/>
        </div>
      </section>

      {/* ── WAITLIST ── */}
      <section className="waitlist-sec" id="waitlist">
        <div className="wbg"/>
        <div className="c">
          <div className="wi">
            <div style={{ display:"inline-flex", alignItems:"center", gap:6, fontSize:".8rem",
              color:"var(--dim)", padding:"6px 14px", background:"var(--faint)",
              borderRadius:"100px", marginBottom:24 }}>
              <span style={{ width:6, height:6, borderRadius:"50%", background:"var(--teal)",
                animation:"blink 2s ease-in-out infinite", display:"block" }}/>
              More readings are coming
            </div>
            <h2 style={{ marginBottom:14 }}>Join <em>1,000+ waitlist</em><br/>members for first access.</h2>
            <p className="sub" style={{ margin:"0 auto 36px", textAlign:"center" }}>
              Compatibility readings, Year Ahead reports, and Gift readings are in development.
              Waitlist members get launch pricing before anyone else.
            </p>
            <div className="wl-cards">
              {UPCOMING.map(u => (
                <div className="wl-card" key={u.title}>
                  <div className="wl-card-badge">Coming Soon</div>
                  <div className="wl-card-title">{u.title}</div>
                  <div className="wl-card-price">{u.price}</div>
                </div>
              ))}
            </div>
            {!submitted ? (
              <form onSubmit={handleWaitlist}
                style={{ maxWidth:"460px", margin:"0 auto", display:"grid", gap:"12px" }}>
                <input className="ei" placeholder="First name" value={wlName}
                  onChange={e=>setWlName(e.target.value)} required/>
                <input className="ei" type="email" placeholder="Email address" value={wlEmail}
                  onChange={e=>setWlEmail(e.target.value)} required/>
                <select className="ei"
                  style={{ background:"#12121e", color:"rgba(232,228,240,0.8)", appearance:"none" }}
                  value={reason} onChange={e=>setReason(e.target.value)}>
                  <option value="Compatibility Reading">Compatibility Reading</option>
                  <option value="Year Ahead Reading">Year Ahead Reading</option>
                  <option value="Gift a Reading">Gift a Reading</option>
                  <option value="All of the above">All of the above</option>
                </select>
                <button className="bp" type="submit" style={{ width:"100%", justifyContent:"center" }}>
                  {wlLoading ? "Joining…" : "Join 1,000+ Waitlist Members →"}
                </button>
                <p className="fn" style={{ textAlign:"center" }}>No spam. Launch pricing ends soon.</p>
              </form>
            ) : (
              <div className="fs">✓ You&apos;re in. Watch your inbox. You&apos;ll be first when it launches.</div>
            )}
          </div>
        </div>
      </section>

      {/* ── FOOTER ── */}
      <footer className="footer">
        <div className="c">
          <div className="fi">
            <div className="fb">
              <a className="logo" href="#"><span className="g">BluntChart</span></a>
              <p>Brutally honest birth chart readings. Real astrology, zero filter, no subscription.</p>
              <div className="slinks">
                <a className="sl2" href="https://www.tiktok.com/@bluntchart" target="_blank" rel="noopener noreferrer">Tk</a>
                <a className="sl2" href="https://www.instagram.com/bluntchart/" target="_blank" rel="noopener noreferrer">In</a>
                <a className="sl2" href="https://www.youtube.com/@BluntChart" target="_blank" rel="noopener noreferrer">Yt</a>
              </div>
            </div>
            <div className="fl">
              <h4>Readings</h4>
              <ul>
                <li><a href="#try-it">Birth Chart · $15</a></li>
                <li><a href="#waitlist">Compatibility · Coming Soon</a></li>
                <li><a href="#waitlist">Year Ahead · Coming Soon</a></li>
                <li><a href="#waitlist">Gift a Reading · Coming Soon</a></li>
              </ul>
            </div>
            <div className="fl">
              <h4>Legal</h4>
              <ul>
                <li><a href="/terms">Terms of Service</a></li>
                <li><a href="/privacy">Privacy Policy</a></li>
                <li><a href="/refunds">Refund Policy</a></li>
              </ul>
            </div>
          </div>
          <div className="fb2">
            <p className="disc">
              For entertainment purposes only. BluntChart readings are not a substitute for
              medical, psychological, financial, or legal advice. Do not make major life
              decisions based solely on astrological content.
            </p>
            <p className="copy">© 2026 BluntChart. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </>
  );
}