"use client";

import { useState } from "react";

const ITEMS = [
  {
    q: "Does this tell me who my future husband is?",
    a: "No. The experience doesn't identify a specific person or predict who you'll marry. It uses relationship themes from your birth chart to create a personalized, imaginative letter written in the voice of a \"future husband.\" Who you picture while reading it is entirely up to you.",
  },
  {
    q: "Can I try this if I'm already in a relationship?",
    a: "Yes. The letter is based on your chart rather than another person's identity, so you can enjoy the experience whether you're single, dating, partnered or married.",
  },
  {
    q: "Is this a birth chart compatibility reading?",
    a: "No. This letter begins with your chart alone. A compatibility reading compares two people's charts. Future Love Letter explores how you love, what you need, and the kind of partner who could fit those patterns — then turns that into a letter.",
  },
  {
    q: "How is this different from zodiac sign compatibility?",
    a: "Zodiac compatibility usually compares two Sun signs. We look at your Moon, Venus, Mars, 7th house, aspects and more — multiple parts of your chart that describe emotional needs, attraction, partnership patterns and internal contradictions. Two Scorpios can need completely different things from love.",
  },
  {
    q: "Is this actually free?",
    a: "Yes. No card, no paywall, no \"unlock paragraph two for $14.99.\" We're testing Future Love Letter as a new experience, so the full thing is free right now.",
  },
  {
    q: "Why do you need my exact birth time?",
    a: "Birth time lets us calculate your Ascendant, houses and relationship axis (the 7th house). Without it, we can still use your planets and aspects, but the reading will be less specific. If you don't know your exact time, your best estimate still helps.",
  },
  {
    q: "Is the letter written by AI?",
    a: "The letter itself is generated by AI, yes — but it's not random. First we calculate your actual birth chart. Then we interpret multiple relationship-relevant placements and aspects into a structured brief. The AI writes from that brief. The astrology is real. The creative writing is AI. We're transparent about both.",
  },
  {
    q: "Does astrology actually predict my future husband?",
    a: "No. This is a personalized creative experience based on astrological interpretation, not a prediction. Your chart can describe relationship patterns, emotional needs and partnership tendencies — and the letter explores what a fitting partner might look and sound like. It's meaningful and personal, but it's not a guarantee.",
  },
  {
    q: "What do you do with my birth data?",
    a: "Your birth details are used server-side to calculate your chart. The chart interpretation is then sent to an AI model to write your letter. We don't sell your data. Check our Privacy Policy for full details.",
  },
  {
    q: "Can I get a letter for someone else?",
    a: "You'd need their birth date, exact birth time and birthplace. If you have those details (with their permission), you can generate a letter using their information.",
  },
];

export default function FAQ() {
  const [openIdx, setOpenIdx] = useState<number | null>(null);

  return (
    <section className="fll-faq">
      <h2 className="fll-section-heading">QUESTIONS</h2>
      <div className="fll-faq-list">
        {ITEMS.map((item, i) => (
          <div
            key={i}
            className={`fll-faq-item ${openIdx === i ? "open" : ""}`}
          >
            <button
              className="fll-faq-q"
              onClick={() =>
                setOpenIdx(openIdx === i ? null : i)
              }
              type="button"
            >
              <span>{item.q}</span>
              <span className="fll-faq-icon">
                {openIdx === i ? "−" : "+"}
              </span>
            </button>
            {openIdx === i && (
              <div className="fll-faq-a">
                <p>{item.a}</p>
              </div>
            )}
          </div>
        ))}
      </div>
    </section>
  );
}
