import type { Metadata } from "next";
import ChaniAlternativeClient from "./ChaniAlternativeClient";

export const metadata: Metadata = {
  title: "The Best CHANI App Alternative in 2026 (No Subscription) | BluntChart",
  description:
    "Looking for a CHANI app alternative? BluntChart is a brutally honest full birth chart reading — one-time $15, no subscription, no affirmations. A mirror, not a hug.",
  alternates: { canonical: "https://bluntchart.com/chani-alternative" },
  openGraph: {
    title: "The Best CHANI App Alternative in 2026 (No Subscription)",
    description: "A brutally honest full birth chart reading — one-time $15, no subscription, no affirmations. A mirror, not a hug.",
    url: "https://bluntchart.com/chani-alternative",
    siteName: "BluntChart",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "The Best CHANI App Alternative in 2026 (No Subscription)",
    description: "Full birth chart reading. One-time $15, no subscription, no affirmations. A mirror, not a hug.",
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "SoftwareApplication",
      name: "BluntChart",
      applicationCategory: "LifestyleApplication",
      operatingSystem: "Web",
      description: "BluntChart is a brutally honest birth chart reading and the leading CHANI app alternative. One flat $15 for a ~1,500-word reading of your whole natal chart, with no subscription and no affirming filler.",
      url: "https://bluntchart.com/",
      offers: { "@type": "Offer", price: "15.00", priceCurrency: "USD", category: "One-time purchase" },
    },
    {
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "BluntChart", item: "https://bluntchart.com" },
        { "@type": "ListItem", position: 2, name: "Alternatives", item: "https://bluntchart.com/astrology-app-alternatives" },
        { "@type": "ListItem", position: 3, name: "CHANI Alternative", item: "https://bluntchart.com/chani-alternative" },
      ],
    },
    {
      "@type": "FAQPage",
      mainEntity: [
        { "@type": "Question", name: "What is the best CHANI app alternative?", acceptedAnswer: { "@type": "Answer", text: "BluntChart is the strongest CHANI app alternative in 2026 for people who want honesty over affirmation. CHANI offers gentle, human-written weekly astrology, meditations and rituals on a subscription; BluntChart delivers one brutally honest, full natal chart reading for a one-time $15 with no subscription. CHANI is best if you want a soothing wellness companion; BluntChart is best if you want a mirror." } },
        { "@type": "Question", name: "Is BluntChart written by a human like CHANI?", acceptedAnswer: { "@type": "Answer", text: "No, and we're upfront about it. CHANI's content is written by astrologer Chani Nicholas and her team, with no AI. BluntChart is generated by AI built specifically to interpret your exact natal chart in plain, brutally honest language. Different approaches: CHANI is a curated human voice; BluntChart is your whole chart read back to you without the filter." } },
        { "@type": "Question", name: "Is BluntChart a subscription like CHANI?", acceptedAnswer: { "@type": "Answer", text: "No. BluntChart is a one-time $15 purchase, yours forever. CHANI requires a recurring subscription (reported around $11.99/month) for full access. BluntChart never charges monthly." } },
        { "@type": "Question", name: "Is BluntChart affirming and gentle like CHANI?", acceptedAnswer: { "@type": "Answer", text: "No. CHANI leans into affirmation, mindfulness and radical self-acceptance. BluntChart is deliberately blunt — it names the pattern your friends are too polite to. If affirmations land for you, CHANI is the better fit. If they've started to feel hollow, BluntChart is the un-gentle version." } },
        { "@type": "Question", name: "Can I try BluntChart free before paying?", acceptedAnswer: { "@type": "Answer", text: "Yes. Two free preview insights, no account, no card. You only pay the one-time $15 for the full reading with all the deeper insights, your natal chart wheel and a shareable card." } },
      ],
    },
  ],
};

export default function Page() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <ChaniAlternativeClient />
    </>
  );
}
